### ISSUE TITLE
**Scenario: Shark can create a shark profile**

### ISSUE THREAD

**Issue by Alejandro-Fuste** [Alejandro-Fuste/JAVA_investing_app#8]
User Story

```
AS A shark
I WANT to be able to create a shark profile
SO THAT I can interact with app

```
* *Acceptance Criteria*

Scenario: Shark can create a shark profile

When The shark clicks on the new profile button
When The shark clicks on drop down list
When The shark clicks on Shark
When The shark enters their first name
When The shark enters their last name
When The shark enters their username
When The shark enters their password
When The shark re-enters their password
When The shark clicks on the create profile button
Then A message saying Account created successfully appears

* *Positive Tests*

1.1: Scenario: Shark creates their account (correct inputs)

* *Negative Tests*

1.2:  Scenario: Shark creates their account (incorrect inputs)

* *Manual Results*

1.1:
  - [x] Pass
  - [ ] Fail

1.2:
  - [x] Pass
  - [ ] Fail

* *Overall Status*
- [x] Complete
- [ ] Incomplete

* *Assigned To*

    Daniel Landeros

**Comment by Virtud87** [comment]
Missing
When The shark enter's their business name
